# Generated by Django 2.2.5 on 2019-11-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_timeslot_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='num_needed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
