# Generated by Django 2.2.5 on 2019-11-19 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_timeslot_num_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='num_signed_up',
            field=models.IntegerField(default=0),
        ),
    ]
