# Generated by Django 2.2.7 on 2019-11-26 20:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Registration', '0004_timeslot_num_signed_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='volunteer',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
