# Generated by Django 2.2.7 on 2019-11-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0005_timeslot_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='Event_Name',
            field=models.CharField(default='x', max_length=100),
            preserve_default=False,
        ),
    ]
