# Generated by Django 2.2.7 on 2019-12-02 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0007_auto_20191202_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 2, 14, 57, 44, 49896)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(default=datetime.time(14, 57, 44, 49916)),
        ),
    ]
