# Generated by Django 2.2.7 on 2019-12-02 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0008_auto_20191202_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 2, 15, 17, 31, 325044)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(default=datetime.time(15, 17, 31, 325064)),
        ),
    ]
