# Generated by Django 2.2.7 on 2019-12-02 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0009_auto_20191202_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 2, 15, 35, 23, 753198)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(default=datetime.time(15, 35, 23, 753219)),
        ),
    ]
