# Generated by Django 2.2.7 on 2019-12-02 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0011_auto_20191202_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='date_time',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='date',
            field=models.DateField(default=datetime.date(2019, 12, 2)),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(default=datetime.time(16, 16, 9, 979749)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(default=datetime.time(16, 16, 9, 979762)),
        ),
    ]
