# Generated by Django 2.2.7 on 2019-12-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0012_auto_20191202_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
