# Generated by Django 2.2.7 on 2019-12-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0014_auto_20191203_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=1024, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address2',
            field=models.CharField(max_length=1024, null=True, verbose_name='Address line 2'),
        ),
    ]
