# Generated by Django 2.2.7 on 2019-12-12 23:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Registration', '0015_auto_20191203_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='corporate_registered_users',
            field=models.ManyToManyField(related_name='corporate_registered_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='corporate_users',
            field=models.ManyToManyField(related_name='corporate_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='opt_in',
            field=models.ManyToManyField(related_name='opt_in', to=settings.AUTH_USER_MODEL),
        ),
    ]
