# Generated by Django 2.2.7 on 2019-12-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0017_auto_20191213_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_code', models.CharField(max_length=3)),
                ('numbers1', models.CharField(max_length=3)),
                ('numbers2', models.CharField(max_length=4)),
            ],
        ),
    ]
