# Generated by Django 2.2.7 on 2019-12-13 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Registration', '0018_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('phone_number', models.ManyToManyField(related_name='phone_number', to='Registration.PhoneNumber')),
                ('user_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='corporate_users',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='opt_in',
        ),
        migrations.AddField(
            model_name='business',
            name='opt_in',
            field=models.ManyToManyField(related_name='opt_in', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='business',
            name='phone_number',
            field=models.ManyToManyField(to='Registration.PhoneNumber'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='corporate_registered_users',
            field=models.ManyToManyField(related_name='corporate_registered_users', to='Registration.CustomUser'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='volunteer',
            field=models.ManyToManyField(to='Registration.CustomUser'),
        ),
        migrations.AddField(
            model_name='business',
            name='corporate_users',
            field=models.ManyToManyField(to='Registration.CustomUser'),
        ),
    ]
