# Generated by Django 2.2.7 on 2019-12-14 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Registration', '0020_auto_20191213_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
