# Generated by Django 2.2.7 on 2019-12-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0021_timeslot_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentTimeSlots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_id', models.IntegerField(default=0)),
                ('current_date', models.DateField(auto_now=True)),
                ('last_update', models.DateField(default='1900-01-01')),
                ('current_timeslots', models.ManyToManyField(to='Registration.TimeSlot')),
            ],
        ),
    ]
